public class Exception {
    public static void main(String [] args){
        int result = 10 / 0;
        try{
            System.out.println("The value is " + result);
        }catch
    }
}